name: Publish VS Code Extension with Changelog Update

on:
    release:
        types: [created]

jobs:
    update_changelog:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Update Changelog
              uses: laravel/.github/.github/workflows/update-changelog.yml@main

    publish:
        runs-on: ubuntu-latest
        needs: update_changelog
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "latest"

            - name: Install dependencies
              run: npm install

            - name: Publish Extension
              env:
                  VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
              run: npx vsce publish -p $VSCE_TOKEN --no-git-tag-version
